### ISSUE TITLE
This is a super useful idea 🥇

### ISSUE THREAD

**Issue by szepeviktor** [TomasVotruba/bladestan#1]
@TomasVotruba You can get some parts of https://github.com/canvural/phpstan-blade-rule

**Comment by TomasVotruba** [comment]
Thanks :)

Already fixing it https://github.com/TomasVotruba/tomasvotruba.com/pull/1384

**Comment by szepeviktor** [comment]
Blade files were always out of control.

**Comment by Wulfheart** [comment]
Oh. This is really cool!

**Comment by TomasVotruba** [comment]
It will be PHPStan extension :+1:

**Comment by freekmurze** [comment]
Looking forward using this 👍
