### ISSUE TITLE
Cache and false positive/negative results

### ISSUE THREAD

**Issue by fabio-ventura** [TomasVotruba/bladestan#103]
Hi,
when I run phpstan, I get results that are not reliable.
To have reliable results I have to delete the cache files:

```
/tmp/*-blade-compiled.php
/tmp/cachegrind.out.*.gz
/tmp/phpstan
```
But I guess it's something inside `/tmp/phpstan`

This only happens for views.

**Comment by AJenbo** [comment]
Duplicate of https://github.com/TomasVotruba/bladestan/issues/85 / https://github.com/TomasVotruba/bladestan/issues/69
