### ISSUE TITLE
The array shape of view() is not picked up if given as a variable

### ISSUE THREAD

**Issue by williamdes** [TomasVotruba/bladestan#107]
```php
        $data = [
            // ...
            'user' => $userBloc->toArray(),
        ];

        $response = view('viewName', $data)->render();
```

It says

```
  185    Undefined variable: $user                                                              
         rendered in: mandat/partials/viewName.blade.php:3 
```

But if I use:
```php
        $response = view('viewName', [
            // ...
            'user' => $userBloc->toArray(),
        ])->render();
```
There is no more error

**Comment by williamdes** [comment]
Same with this pattern

```php

        return $this->to('admin@xxxx.xx')
            ->subject('Title here:' . $this->ressourceId)
            ->view('email.payinFailed')
            ->with([
                'payinId' => $this->ressourceId,
            ]);
```

```
  41     Variable $payinId might not be defined.             
         rendered in: email/payinFailed.blade.php:13  
```

**Comment by williamdes** [comment]
@TomasVotruba I am willing to do a one time sponsoring of $50 to get this issue fixed as I really need to have phpstan working for my blade templates (incoming refactoring)
Is that okay for you ?

**Comment by AJenbo** [comment]
> Same with this pattern
> 
> ```
>         return $this->to('admin@xxxx.xx')
>             ->subject('Title here:' . $this->ressourceId)
>             ->view('email.payinFailed')
>             ->with([
>                 'payinId' => $this->ressourceId,
>             ]);
> ```

This one might be simple to solve since it's supported on the global `view()` function: https://github.com/TomasVotruba/bladestan/blob/53e514cd891ed059a7f8259edd6f5165fe4a23f6/tests/Rules/Fixture/laravel-view-function.php#L22

**Comment by TomasVotruba** [comment]
@williamdes Thanks :+1:  Make sure you sponsor @AJenbo, he's the main contributor last couple of years :muscle:

**Comment by AJenbo** [comment]
I'm not really setup to take sponsor ships and I maintain it though my employer so not sure how that would work.
If any one else is interested in implementing the feature and receiving the sponsor ship then I'm at least happy to do review and support of it.

**Comment by williamdes** [comment]
> I'm not really setup to take sponsor ships and I maintain it though my employer so not sure how that would work. If any one else is interested in implementing the feature and receiving the sponsor ship then I'm at least happy to do review and support of it.

Definitely check if you can setup GH sponsors or send me a PayPal link for a donation 👍👍💪

**Comment by AJenbo** [comment]
Sorry this conflicts with my employment.

**Comment by williamdes** [comment]
> Sorry this conflicts with my employment.

That's okay, I totally understand

**Comment by AJenbo** [comment]
What's your horizon on needing this ?

**Comment by williamdes** [comment]
> What's your horizon on needing this ?

I would say this week of the next one
I did not find a phpdoc hack to workaround this bug :/
Definitely feeling terrible for putting deadlines on an open source project..

**Comment by AJenbo** [comment]
If no one else picks up the bounty I might take a stab at it in the next 2-3 weeks.

**Comment by mrhn** [comment]
Met @AJenbo at a conference as he is my old coworker, someone talked about PHPParsing, this was mentioned and i gave it a try with this [PR](https://github.com/TomasVotruba/bladestan/pull/108). There was some new challenges compared to some of the other analyzers they made, so we probably need some changes to make it more "non hacky". 

But there is hope out there and the testcase i made passed, similar to the first example you had, if we get that PR moving i would gladly take a look at the other example you presented.

**Comment by williamdes** [comment]
Awesome @mrhn
Let me know when you want that I test the PR, even in draft state 
I made a separate baseline file so it's easy to spot un handled cases

**Comment by AJenbo** [comment]
> Same with this pattern
> 
> ```
>         return $this->to('admin@xxxx.xx')
>             ->subject('Title here:' . $this->ressourceId)
>             ->view('email.payinFailed')
>             ->with([
>                 'payinId' => $this->ressourceId,
>             ]);
> ```
> 
> ```
>   41     Variable $payinId might not be defined.             
>          rendered in: email/payinFailed.blade.php:13  
> ```

With out knowing what class type this code appears in we won't really know what the issue might be here or how to solve it. I'm guessing it's a `Illuminate\Mail\Mailable`? Have you tried changing the code to this:

> ```php
>         return $this->view('email.payinFailed')
>             ->with([
>                 'payinId' => $this->ressourceId,
>             ])->to('admin@xxxx.xx')
>             ->subject('Title here:' . $this->ressourceId);
> ```

If that works then it's more likely that the return value of `to()` or `subject()` are not properly hinted in Laravel/Larastan and so the call to `view()` looks like it's not a known blade function.

**Comment by AJenbo** [comment]
Fixed by https://github.com/TomasVotruba/bladestan/pull/108
