### ISSUE TITLE
TomasVotruba\Bladestan\Exception\ShouldNotHappenException was caught

### ISSUE THREAD

**Issue by johntheteam** [TomasVotruba/bladestan#110]
Reported to phpstan, they said this is the problem of bladestan.
https://github.com/phpstan/phpstan/issues/11520

As Bladestan is only used to do checks for potential issues, I think it's better to pass silently instead of throwing exceptions that are hard to solve.

**Comment by AJenbo** [comment]
Duplicate https://github.com/TomasVotruba/bladestan/issues/92
