### ISSUE TITLE
README typo formatter option 

### ISSUE THREAD

**Issue by Andreas-Halemba** [TomasVotruba/bladestan#18]
shouldn't 

`vendor/bin/phpstan --error-format blade`

be

`vendor/bin/phpstan --error-format=blade`

as I get 

`Command "blade" is not defined. `

**Comment by TomasVotruba** [comment]
Once you change options, the `analyze` command must be explicitly added.

**Comment by szepeviktor** [comment]
Fixed in #23

**Comment by TomasVotruba** [comment]
Yep, thanks :+1:
