### ISSUE TITLE
component support?

### ISSUE THREAD

**Issue by AJenbo** [TomasVotruba/bladestan#27]
canvural/phpstan-blade-rule has a not in the readme:
> Blade components are not analyzed. Support for it will come soon.

Has this been reolved since it does not appear?

I noticed that the following will produce an error:

```php
<?php

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class MyComponent extends Component
{
    public string $test;

    public function render(): View
    {
        return view('components.my-component');
    }
}
```

`Variable $test might not be defined.`

**Comment by TomasVotruba** [comment]
Hi, this is not supported yet. The view must have defined type and passed variables:

```php
return view('components.my-component', [
     'test' => $this->test
]);
```

E.g. the `$test` in your example would throw fatal error, as is nullable and not defined since constuctor.

**Comment by AJenbo** [comment]
That's fair (and also the solution i went with). Another issue I found with components is that if i change `view()` for `$this->view()` it doesn't analyze the blade at all and just says there are no issues in the component.

**Comment by TomasVotruba** [comment]
Test fixture pull-request would the most helpful :)

**Comment by AJenbo** [comment]
Once I have grouped the various issues I will start creating a mvp project that can trigger these issues and submit it :)

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Instead of project, I mean a test fixture in here - https://github.com/TomasVotruba/bladestan/blob/b1e4a45d9180b743e74b439bf6ddb6e063986f9c/tests/Rules/LaravelViewFunctionRuleTest.php#L54, so we have it covered and see the errors :)

**Comment by AJenbo** [comment]
Well, one step at a time :)

**Comment by AJenbo** [comment]
I guess my question was answered, just maybe not the one i stated in the title :)
