### ISSUE TITLE
Add support for response()->view()

### ISSUE THREAD

**Issue by joelclermont** [TomasVotruba/bladestan#32]
I scanned a few of my current projects, and over 99% of the time I'm returning a view from a controller, I use the global `view()` helper, but that < 1% would be nice to cover too.

Sometimes if you need to set a response header or alter the status code, I'll use `Response::view()` or `response()->view()`.

I'm contemplating standardizing on response()->view() since it returns a concrete `Response` type, whereas the global view helper returns a much larger union type.

**Comment by TomasVotruba** [comment]
Thanks for the suggestion :+1: 

Could you add a new fixture with single minimal example here?
https://github.com/TomasVotruba/bladestan/tree/main/tests/Rules/Fixture

**Comment by TomasVotruba** [comment]
Done in https://github.com/TomasVotruba/bladestan/pull/37
