### ISSUE TITLE
BladeRule not found

### ISSUE THREAD

**Issue by paddockDev** [TomasVotruba/bladestan#35]
Now that I have Bladestan up and running, I run into the next problem.

```
In Resolver.php line 111:
                                                                                  
  Service 'rules.150': Class 'TomasVotruba\Bladestan\Rules\BladeRule' not found.
```

**Comment by TomasVotruba** [comment]
That's very unlikely to happen. We'll need a reproducer repository.

**Comment by paddockDev** [comment]
@TomasVotruba With the new version my problem is now fixed and bladestan and larastan can be used together.
