### ISSUE TITLE
setup documentation: add phpstan.neon includes

### ISSUE THREAD

**Issue by ghbob** [TomasVotruba/bladestan#38]
Couldn't find it in the blogpost [(1)](https://tomasvotruba.com/blog/introducing-bladestan-phpstan-analysis-of-blade-templates/) nor the readme [(2)](https://github.com/TomasVotruba/bladestan#readme) but one actually has to require the extension to run bladestan with phpstan, correct?

Otherwise I immediately run into:

```bash
Invalid configuration:
Unexpected item 'parameters › bladestan'.
```

therefore e.g.
```neon
includes:
    - ./vendor/tomasvotruba/bladestan/config/extension.neon
    - ./vendor/phpstan/phpstan-strict-rules/rules.neon
    - ./vendor/nunomaduro/larastan/extension.neon
```

Thanks!

**Comment by TomasVotruba** [comment]
Yes, always use the PHPStan extension installer.
Not for this project only, but any other PHPStan extension. It will save you from so much config copying.

https://github.com/phpstan/extension-installer

**Comment by TomasVotruba** [comment]
If you have time and it's not much troubles for you, could you send PR to readme to clarify it?

**Comment by TomasVotruba** [comment]
> However it apparently enables everything and if I enable all the phpstan-strict-rules my co-workers will murder me in my sleep ;)

Yes, you should only install the extensions you need :wink:
