### ISSUE TITLE
File ends with a trailing whitespace.

### ISSUE THREAD

**Issue by realodix** [TomasVotruba/bladestan#42]
What can I do to fix this error?

![noname-crop](https://user-images.githubusercontent.com/1314456/230038523-901f887f-bde0-4fae-b2fd-95877b017c33.png)

```sh
-- ----------------------------------------------------------------------------------------------------------------------
Error
-- ----------------------------------------------------------------------------------------------------------------------
Internal error: Internal error: config in file G:\laragon\www\urlhub\app\Http\Middleware\RedirectIfAuthenticated.php
Run PHPStan with -v option and post the stack trace to:
https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
Child process error (exit code 1):
Internal error: Internal error: config in file G:\laragon\www\urlhub\app\Providers\RouteServiceProvider.php
Run PHPStan with -v option and post the stack trace to:
https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
Child process error (exit code 1):
```

But, When I disabled Bladestan, there is no error

![noname-craop](https://user-images.githubusercontent.com/1314456/230039886-a98bd54f-e052-4594-af3c-2b4130bed17b.png)

**Comment by AJenbo** [comment]
A decent portion of the files in the project I work on is also affected by this.

From what I can tell it happens if you have blade files with no code in them (just static content). I added a test for this so hopeful that will help someone look in to the issue: #45
