### ISSUE TITLE
How to use Bladestan? resources/views vs. app

### ISSUE THREAD

**Issue by szepeviktor** [TomasVotruba/bladestan#44]
What is the intended usage? May I use both? What is the real difference in findings?
```bash
phpstan analyze -c vendor/tomasvotruba/bladestan/config/extension.neon -l max resources/views/
phpstan analyze -c vendor/tomasvotruba/bladestan/config/extension.neon -l max app/
```

**Comment by szepeviktor** [comment]
I think Bladstan works by analyzing .php files in app/ as resources/views/ don't have template variables.

I need to work on E2E tests.
Would you merge it?

**Comment by TomasVotruba** [comment]
Yes, that's why no change is needed in typical setup.

Feel free to send it, sure 👍
